services:
  api:
    build: ./api
    ports:
      - "${API_PORT}:5000"
    restart: on-failure
    volumes:
      - ./shared:/shared
    env_file:
      - .env

  emulator:
    build: ./pyboy
    restart: on-failure
    volumes:
      - ./shared:/shared
      - ./pyboy/save:/save